# Generated by Django 3.2.25 on 2024-10-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
